Repository hassio-addons/addon-grafana, pull requests merged in 2021-04, with the labels that each got.

#134 Add access to Home Assistant configuration so SQLite DB can be used
  grafana/config.json
Labels: new-feature

#136 ⬆️ Upgrades Grafana to v7.5.3
  grafana/Dockerfile
Labels: dependencies

#135 ⬆️ Upgrades add-on base image to v4.1.4
  grafana/Dockerfile
  grafana/build.json
Labels: dependencies

#129 Add /health as watchdog url
  grafana/config.json
Labels: new-feature

#101 Document anonymous access and limitations
  grafana/DOCS.md
Labels: documentation

#138 📚 Update docs in reference to password change
  grafana/DOCS.md
Labels: documentation

#139 ⬆️ Upgrades Grafana to v7.5.4
  grafana/Dockerfile
Labels: dependencies

#142 Upgrades add-on base image to v4.2.0
  grafana/Dockerfile
  grafana/build.json
Labels: dependencies

#143 Apply updated repository structure & CI workflow
  .editorconfig
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/pr-labels.yaml
Labels: ci

#144 📚 Correct anonymous variables
  grafana/DOCS.md
Labels: documentation

#148 ⬆️ Upgrades Grafana to v7.5.5
  grafana/Dockerfile
Labels: dependencies
