Repository hassio-addons/addon-grafana, pull requests merged in 2021-11, with the labels that each got.

#224 Switch to centralized GitHub Action Workflows
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#225 Migrate JSON config to YAML
  grafana/build.json
  grafana/build.yaml
  grafana/config.json
  grafana/config.yaml
Labels: refactor

#226 ⬆️ Upgrades add-on base image to 5.2.0
  grafana/Dockerfile
  grafana/build.yaml
Labels: dependencies

#202 docker install CJK font support grafana-image-renderer
  grafana/Dockerfile
Labels: bugfix

#227 ⬆️ Upgrades add-on base image to 5.2.2
  grafana/Dockerfile
  grafana/build.yaml
Labels: dependencies

#228 ⬆️ Upgrades Grafana to v8.2.3
  grafana/Dockerfile
Labels: dependencies

#229 ⬆️ Upgrades Grafana Image Renderer to 3.2.1
  grafana/Dockerfile
Labels: dependencies

#230 🔨 Add libxshmfence1 v1.3-1 for Image Renderer
  grafana/Dockerfile
Labels: bugfix

#234 ⬆️ Upgrades Grafana Image Renderer to 3.3.0
  grafana/Dockerfile
Labels: dependencies

#235 ⬆️ Upgrades Grafana to v8.2.5
  grafana/Dockerfile
Labels: dependencies
