Repository hassio-addons/addon-grafana, pull requests merged in 2022-03, with the labels that each got.

#250 ⬆️ Upgrades add-on base image to 5.3.0
  grafana/Dockerfile
  grafana/build.yaml
Labels: dependencies

#251 :lock: Sign add-on with Codenotary Community Attestation Service (CAS)
  .github/workflows/deploy.yaml
  grafana/build.yaml
  grafana/config.yaml
Labels: enhancement

#253 :books: Add My buttons to documentation
  grafana/DOCS.md
Labels: documentation

#252 ⬆️ Upgrades Grafana to v8.4.3
  grafana/Dockerfile
Labels: dependencies

#249 Enables Grafana unified alerting and disables legacy dashboard alerting
  grafana/rootfs/etc/grafana/grafana.ini
Labels: new-feature

#254 ⬆️ Upgrades Grafana Image Renderer to 3.4.1
  grafana/Dockerfile
Labels: dependencies

#256 ⬆️ Upgrades Grafana to v8.4.4
  grafana/Dockerfile
Labels: dependencies

#257 ⬆️ Upgrades Grafana Image Renderer to 3.4.2
  grafana/Dockerfile
Labels: dependencies
