Repository hassio-addons/addon-grafana, pull requests merged in 2023-07, with the labels that each got.

#336 Replace watchdog with Docker health check
  grafana/Dockerfile
  grafana/config.yaml
Labels: enhancement

#331 Allow installation of unsigned plugins using an URL
  grafana/DOCS.md
  grafana/config.yaml
  grafana/rootfs/etc/grafana/grafana.ini
  grafana/rootfs/etc/s6-overlay/s6-rc.d/grafana/run
  grafana/rootfs/etc/s6-overlay/s6-rc.d/init-grafana/run
Labels: new-feature

#339 Fix health check
  grafana/rootfs/etc/nginx/servers/ingress.conf
Labels: bugfix

#340 Remove nginx ingress server listening on a single interface
  grafana/rootfs/etc/nginx/servers/ingress.conf
  grafana/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/run
Labels: bugfix
