Repository hassio-addons/addon-grafana, pull requests merged in 2023-03, with the labels that each got.

#303 :fireworks: Updates maintenance/license year to 2023
  LICENSE.md
  README.md
  grafana/.README.j2
  grafana/DOCS.md
Labels: maintenance

#304 ⬆️ Upgrades add-on base image to 6.2.3
  grafana/Dockerfile
  grafana/build.yaml
Labels: dependencies

#305 ⬆️ Upgrades Grafana to v9.4.3
  grafana/Dockerfile
Labels: minor, dependencies

#306 ⬆️ Upgrades Grafarafana Image Renderer to 3.6.4
  grafana/Dockerfile
Labels: dependencies

#313 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  grafana/Dockerfile
Labels: maintenance

#317 Fix broken URL
  grafana/DOCS.md
Labels: documentation
